Prevent Amazon Link Cloaking
mollusk/simple-urls pull request #27
Opened 2021-02-26 18:55 UTC by mollusk

Users may place monetized Amazon links in Simple URLs for easy referencing in posts. However, currently, Simple URLs will cloak Amazon links which is against their TOS, and can get an affiliate banned from the Amazon Associates program. This PR fixes that.

### How to test
1. Create a Simple URL with a link to Amazon from any of their core domains (.com, .co.uk, etc...)
2. Insert into post through the integrated WordPress linking tool.

2021-03-02 17:54 UTC, kienstra commented
Hi @mollusk,
Thanks for this!

It looks to work in the Classic Editor:
![it-is-a](https://user-images.githubusercontent.com/4063887/109691725-5beeb180-7b4d-11eb-81c1-5c1c788f566c.gif)

Could users just manually enter the Amazon link, without using this plugin at all?

![entering-link-manually](https://user-images.githubusercontent.com/4063887/109692195-d9b2bd00-7b4d-11eb-95a2-34dd37863f80.gif)

The Simple URLs menu still shows permalinks for those Amazon links, even though the editor will only have the Amazon URL, not the permalink:

<img width="990" alt="still-has-a-blink" src="https://user-images.githubusercontent.com/4063887/109692064-b2f48680-7b4d-11eb-8c78-924ae7569981.png">

2021-03-02 17:54 UTC, kienstra requested changes

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +		$parse_url = wp_parse_url( $url );
```suggestion
		$parsed_url = wp_parse_url( $url );
```

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +	 * @param string $url URL.
Probably a `@return` tag here also

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +	public static function get_domains() {
Does these functions need to be `static` ?

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +			'amazon.com',           // ? US
What are the `?` for, like `? US` ?

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +	 * @param string $url Url.
Probably a `@return` tag also

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +	 * @param string $url URL.
Probably a `@return` tag also

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +		if ( strpos( $url, 'http://' ) !== 0 && strpos( $url, 'https://' ) !== 0 ) {
Instead of this block, maybe:

```php
preg_replace( '#^http(?=://)#', 'https', $url );
```
From https://github.com/GoogleChromeLabs/pwa-wp/blob/739d1f1d8bf49401a564d35b232a948f894585d9/wp-includes/class-wp-https-ui.php#L324

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +				if ( self::is_amazon_url($redirect) ) {
```suggestion
				if ( self::is_amazon_url( $redirect ) ) {
```

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +					// ? set Amazon product url
```suggestion
					// Set Amazon product url
```

2021-03-02 17:54 UTC, kienstra commented on includes/class-simple-urls.php
> +			'amazon.co.uk',         // ? UK
Is there a way to avoid enumerating all of the country top-level domains, like `.co.uk`, `.com.au`, `.com.br`, etc?

2021-03-03 16:43 UTC, mollusk commented on includes/class-simple-urls.php
> +				$post_id    = $post['ID'];
@kienstra Agreed, thank you for catching that.

2021-03-03 16:44 UTC, mollusk commented on includes/class-simple-urls.php
> +		if ( count( $results ) > 0 ) {
@kienstra I didn't realize that, stuck it in there to confirm it was an array. Less lines = better.

2021-03-03 16:45 UTC, mollusk commented on includes/class-simple-urls.php
> +		$parse_url = wp_parse_url( $url );
@kienstra Read better, thank you, fixed it.

2021-03-03 16:46 UTC, mollusk commented on includes/class-simple-urls.php
> +	public static function get_domains() {
@kienstra The reason this is static is that I can see in the future it being used in another class potentially without instantiating the class. I might even peel things like this out of the core class when we grow.

2021-03-03 16:49 UTC, mollusk commented on includes/class-simple-urls.php
> +			'amazon.com',           // ? US
@kienstra phpcs, old habits die hard ;) I think some short-term next steps are getting the repo hooked into CircleCI w/GitHub Actions and *at least* attaching a phpcs validator to keep everything tight as the codebase grows. Unit Tests should ideally be done in the same PR along with hooking into Coveralls. Won't pretend to see everything, great code coverage is a big stress reducer (and weekend saver).

2021-03-03 16:49 UTC, mollusk commented on includes/class-simple-urls.php
> +	 * @param string $url URL.
@kienstra Done.

2021-03-03 16:49 UTC, mollusk commented on includes/class-simple-urls.php
> +	 * @param string $url Url.
@kienstra Done.

2021-03-03 16:50 UTC, mollusk commented on includes/class-simple-urls.php
> +	 * @param string $url URL.
Done.

2021-03-03 16:51 UTC, mollusk commented on includes/class-simple-urls.php
> +		if ( strpos( $url, 'http://' ) !== 0 && strpos( $url, 'https://' ) !== 0 ) {
@kienstra That's really elegant, thank's for sharing. Upgraded these lines. Did you just seek that out? GoogleChrome reference is kinda next level.

2021-03-03 16:51 UTC, mollusk commented on includes/class-simple-urls.php
> +				if ( self::is_amazon_url($redirect) ) {
Done.

2021-03-03 16:53 UTC, mollusk commented on includes/class-simple-urls.php
> +					// ? set Amazon product url
Another phpcs habit. I don't think things like .se are immediately obvious that it's Sweden. Ask me in a year and I'll probably have no clue, just trying to not re-think things like this.

2021-03-03 16:55 UTC, mollusk commented on includes/class-simple-urls.php
> +			'amazon.co.uk',         // ? UK
@kienstra Not that I'm aware of, I mean there could be an API somewhere but Amazon onboards new locales so slowly that I don't think this will be an issue. If we add in Product API support then it will be manual work anyways (local endpoints URLs and datacenter slugs need to be looked up).

2021-03-03 17:06 UTC, mollusk commented
@kienstra Thanks for taking the time to review this PR, I very much appreciate it. I know you've got a lot more pressing work to deal with.

First, I'm just curious, how did you make those gifs?

> Could users just manually enter the Amazon link, without using this plugin at all?

Of course, but I don't see the value of SimpleURLs as simply a link cloaking tool. People don't actively seek out cloaking, it's usually to solve a problem. The level 1 problem is to abstract a URL, I think the level 2 problem is maintaining an inventory of links that you care about. 

On my affiliate sites we tend to set up a relationship (or decide on a product/book) and then we reuse it everywhere. Granted you're not cloaking the URL, I think you'll want to look up a book like "I Will Teach You to Be Rich" as often, if not more so, than a post/page for an internal link. So IMHO, taking this approach makes hitting the publish button that much easier in the long-term.

The reason I left the other URL in the report is I do see some use-cases for having a shortened URL. For example, you can remember it and then just say it on a podcast. We do this a lot on our show and it works really well. Perhaps when we add things like tooltips/education in I'll mention that all uses of Amazon URLs on the site will not be cloaked. Don't want to include too much information in the UI that most users don't care about.  

For example, when I hit enter in this GitHub comment box there aren't any notifications or disclaimers that say my Comment won't be submitted (unlike a chat tool that would submit after hitting enter). Things like that are assumed with great tools, I think complying with Amazon's TOS should be an assumption for users, and for those nervous, we can have educational components that reassure them.

2021-03-03 17:15 UTC, kienstra commented on includes/class-simple-urls.php
> +			'amazon.com',           // ? US
Good point! Ah, I didn't know about `?`.

2021-03-08 18:25 UTC, kienstra requested changes
Hi @mollusk,

Thanks for your patience here. A few very minor points, but these are the last suggestions I have.

>The reason I left the other URL in the report is I do see some use-cases for having a shortened URL. For example, you can remember it and then just say it on a podcast. We do this a lot on our show and it works really well. Perhaps when we add things like tooltips/education in I'll mention that all uses of Amazon URLs on the site will not be cloaked. Don't want to include too much information in the UI that most users don't care about.

Good point, your experience with this plugin helps a lot to show why this PR is useful.

2021-03-08 18:26 UTC, kienstra commented on includes/class-simple-urls.php
> +				// ? set Amazon product url
Like you mentioned, setting up linting on CI/CD like CircleCI would be good.

2021-03-08 18:35 UTC, kienstra commented on includes/class-simple-urls.php
> +			'amazon.com',           // ? US
Good idea about running CI/CD. Maybe CircleCI isn't set up for this repo, though as you saw it has a [.circleci/config.yml](https://github.com/studiopress/simple-urls/blob/6e9030005f7e58b8ceca79a8a7eba992c7a3f85a/.circleci/config.yml).

It only took about an hour to set up GitHub actions in [one of my plugins](https://github.com/kienstra/headless-blocks/tree/d54a60f79b6949cb41ca4dea5152b92d7288f276/.github/workflows), maybe that'd be a quick win.

2021-03-09 18:45 UTC, kienstra commented
## Thanks, looks good!

@mollusk,
Thanks a lot for making those changes.

This still works as expected in the Classic editor.

On entering an Amazon URL, it's the plain URL, not the permalink:
<img width="617" alt="non-cloaked-link" src="https://user-images.githubusercontent.com/4063887/110521085-f1052380-80d4-11eb-9482-d6c14877c1c9.png">

For the changelog when this is released, it'd be good to note that this PR applies only to the Classic editor, unless I missed something.

2021-03-09 18:45 UTC, kienstra approved these changes

2021-04-01 13:39 UTC, johnstonphilip approved these changes
Looks good here.

2021-06-17 16:36 UTC, merged